server:
  port: ${AUTH_SERVICE_PORT:8000}
app:
  name: "@project.name@"
  version: "@project.version@"
  description: "@project.description@"
  artifact: "@project.artifactId@"
  group: "@project.groupId@"

spring:
  application:
    name: "@project.name@"

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:demo-app }
            client-secret: ${KEYCLOAK_CLIENT_SECRET:rdGLEw4CColzVYbsUD7wjmicKNOve8pX }
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/demo-realm}
            user-name-attribute: preferred_username

logging:
  level:
    org:
      springframework:
        security:
          oauth2: DEBUG